import time
ESC = '\x1b'
print(ESC + "[32mDerpi Gaem Loading for exactly 5 seconds!!!0! Ples Wait")
time.sleep(5)
print(ESC + "[32mWelcome!")
print(r"-----", end='\r')
time.sleep(1)
print(r"\----", end='\r')
time.sleep(1)
print(r"|----", end='\r')
time.sleep(1)
print(r"/----", end='\r')
time.sleep(1)
print(r"-----", end='\r')
time.sleep(1)
print(r"\----", end='\r')
time.sleep(1)
print(r"#|---", end='\r')
time.sleep(0.10)
print(r"##|--", end='\r')
time.sleep(0.80)
print(r"##/--", end='\r')
time.sleep(1)
print("#####")
print("The loading screen was fake.")
print("Welcome to my gaem")
charname = input("Name your character >>>")
print(f"Hello, {charname}!")
skills = input("Enter your skills. It can be anything you want it to be >>>")
skilldesc = input("Describe your skill: Enter 1 for fire skill, Enter 2 for earth skill, enter 3 for magic skill, enter 4 for Dark Magic skill, Enter 5 for Black hole. >>>")
if skilldesc == "1":
    
